<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The input layer is one of two layers that are very easily interpreted and can be seen easily. This is the layer that holds all of the inputs(data with features) that we are including in the model.

(note that this input layer includes ALL the features, because we don't have to do feature engineering with neural nets)

### Hidden Layer:
The hidden layer(s) are the layers of nodes inside of the models that are transforming the input layer and each subsequent hidden layer after that. They can only be accessed through the input layer

### Output Layer:
The output layer holds all of the predictions, and a specific number that predicts how likely it is that the input is related to that class.

outputs a vector of values that holds our predictions.

if regression: usually we don't need an activation function on our output node because the value we get in our output layer is just a continious number

if binary classification: the activation funciton at the output node is usually a sigmoidal function to give a probability of predicting a specific class

multi class classification: most of the time uses "softmax function"... not sure wut this is

### Neuron:
there are a specific number of neurons in each layer. in the input layer, the number of neurons is the number of features the input data has for a given observation. for the output layer, the number of neurons is the number of class

### Weight:
weights, along with bias, transform our data in (hopefully) a meaningful way so that we are better able to make sense of the inputs. At each node in the model there is a different weight associated with it with then feeds into the next layer.

The model "learns" by seeing how far the predicted output is from the actual value, and then tweaking the weights accordingly. 


### Activation Function:
The activation function takes the outputs given from the previous layer and transforms them to extract new information. 

Each node has an activation function. Usually in a single layer, each node has the same activation function.

The activation funciton is what allows how much signal to be passed on to the next layer

# Question:
Why would each node in any given layer have the same activation funciton? wouldn't it make sense for them all to have different functions so that they could all have different outputs? 


### Node Map:
node maps are mapping the inputs to the specific nodes that they activate

### Perceptron:
The perceptron is the most simple kind of neural network. It only has one node. it takes inputs and spits out an output. 

Takes all inputs, multiplies each by their corresponding weights, adds the bias, and then the sum of all of this gets passed through the activation function which gives the final value... simple because it only has one node. 

Good for two-class classification problems.

Can you also use it for regression problems????? (in the same way but without an activation function at the end)


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [11]:
import pandas as pd

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [30]:
inputs = df.loc[:,['x1', 'x2']].values
correct_outputs = df.loc[:,['y']].values

In [31]:
import numpy as np

# sigmoid activation functions + derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [32]:
# initialize random weights for our two inputs
# ????? where did this equation come from??????
weights = 2 * np.random.random((2,1)) - 1
weights

array([[-0.04147145],
       [-0.6413701 ]])

In [33]:
# get weighted sum of inputs and weights
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[ 0.        ],
       [-0.04147145],
       [-0.6413701 ],
       [-0.68284155]])

In [34]:
# output activated value for end of 1 training epoch
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.48963362],
       [0.34493689],
       [0.33562739]])

In [35]:
# calculate error score
error = correct_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.51036638],
       [ 0.65506311],
       [-0.33562739]])

In [36]:
# gradient descent
adjustments = error * sigmoid_derivative(weighted_sum)
adjustments

array([[ 0.125     ],
       [ 0.12753675],
       [ 0.14801507],
       [-0.07483875]])

In [37]:
weights += np.dot(inputs.T, adjustments)
weights

array([[ 0.01122655],
       [-0.56819378]])

In [38]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 1.52655666e-16]
 [-3.19189120e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


In [ ]:
# ???? l o l 

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [2]:
import pandas as pd

In [47]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [48]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats]
y_vector = diabetes['Outcome']

In [49]:
transformer = Normalizer()

X_matrix = transformer.fit_transform(X)

In [59]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
        # self.rate = rate
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        return sx * (1-sx)

    def fit(self, X, y):
        """
        Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        weights = 2 * np.random.random((8,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(inputs, weights)

            # Activate!
            activated_output = sigmoid(weighted_sum)

            # Cac error
            error = correct_outputs - activated_output

            # Update the Weights
            adjustments = error * sigmoid_derivative(weighted_sum)
            weights += np.dot(inputs.T, adjustments)


    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, weights)
        activated_output = self.__sigmoid(weighted_sum)
        return [1 if n > 0.5 else 0 for n in activated_output]

In [60]:
model = Perceptron(niter=250)

In [62]:
model.fit(X_matrix, y_vector)

ValueError: shapes (4,2) and (8,1) not aligned: 2 (dim 1) != 8 (dim 0)

In [ ]:
# Get model accuracy
from sklearn.metrics import accuracy_score


y_pred = model.predict(X_test)
accuracy = accuracy_score(y_pred, y_test)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?